AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: wordle/quordle
Globals:
  Function:
    Timeout: 900
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*.ramakocherlakota.net'''
Resources:
  WordleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://wordle-lambda-code/d2bb14b3a958c39f54a75ae00bff7696
      Handler: lambda.handler
      MemorySize: 10000
      Runtime: python3.9
      FunctionUrlConfig:
        AuthType: NONE
      VpcConfig:
        SecurityGroupIds:
        - sg-08f16b195b617b692
        SubnetIds:
        - subnet-05390b4b204fd772e
      FileSystemConfigs:
      - Arn: arn:aws:elasticfilesystem:us-east-1:111144063151:access-point/fsap-069fbd36c4a047102
        LocalMountPath: /mnt/efs
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - elasticfilesystem:ClientMount
          - elasticfilesystem:ClientRootAccess
          - elasticfilesystem:ClientWrite
          - elasticfilesystem:DescribeMountTargets
          Resource: '*'
    Metadata:
      SamResourceId: WordleFunction
